name = "DiskCollections"
uuid = "5dc218a2-50e6-48ce-82bf-e5f7008f86a6"
authors = ["Johannes Ahnlide <johannes@voxel.se> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
